#!/usr/bin/env python3
"""
gen_readme.py — auto-generate README.md from source Doxygen comments.

Reads @brief tags from each src/*.h and @file, plus #define ///< entries
from config.h, and writes a formatted README.md to the project root.

Usage (from project root):
    python scripts/gen_readme.py
"""

import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'src')
OUT  = os.path.join(ROOT, 'README.md')


# ── Helpers ────────────────────────────────────────────────────────────────────

def file_brief(path):
    """Return the @brief text from the file-level Doxygen block."""
    text = open(path, encoding='utf-8').read()
    m = re.search(r'@brief\s+(.+?)(?:\n \*|\n\*/)', text, re.DOTALL)
    if m:
        return re.sub(r'\s+', ' ', m.group(1)).strip()
    return ''


def config_defines(path):
    """Return list of (name, value, comment) for every #define with a ///< comment."""
    rows = []
    for line in open(path, encoding='utf-8'):
        m = re.match(r'\s*#define\s+(\w+)\s+(\S+)\s+///< (.+)', line)
        if m:
            rows.append((m.group(1), m.group(2).strip('"'), m.group(3).strip()))
    return rows


def md_table(headers, rows):
    """Render a GitHub-flavoured markdown table."""
    widths = [
        max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
        for i, h in enumerate(headers)
    ]
    def fmt_row(cells):
        return '| ' + ' | '.join(str(c).ljust(widths[i]) for i, c in enumerate(cells)) + ' |'
    sep = '| ' + ' | '.join('-' * w for w in widths) + ' |'
    return '\n'.join([fmt_row(headers), sep] + [fmt_row(r) for r in rows])


# ── Module table ───────────────────────────────────────────────────────────────

MODULE_ORDER = [
    'main.cpp',
    'config.h',
    'globals.h',
    'globals.cpp',
    'prefs.h',
    'fan.h',
    'temperature.h',
    'pid_control.h',
    'status_led.h',
    'dashboard.h',
    'provisioning.h',
]

module_rows = []
for name in MODULE_ORDER:
    path = os.path.join(SRC, name)
    if os.path.exists(path):
        brief = file_brief(path)
        if brief:
            module_rows.append((f'`{name}`', brief))


# ── Pin/constant tables from config.h ─────────────────────────────────────────
# Provisioning secrets come from config_local.h.example (the committed template)
# so the README never exposes real values.

cfg_path      = os.path.join(SRC, 'config.h')
cfg_local_ex  = os.path.join(SRC, 'config_local.h.example')

defines = config_defines(cfg_path)
defines += config_defines(cfg_local_ex)

pins   = [(n, v, c) for n, v, c in defines if 'PIN' in n]
timing = [(n, v, c) for n, v, c in defines if 'MS' in n]
prov   = [(n, v, c) for n, v, c in defines if 'PROV' in n]


# ── Write README ───────────────────────────────────────────────────────────────

readme = f"""\
<!-- AUTO-GENERATED by scripts/gen_readme.py — edit the script, not this file -->
# Vishes Seedling Fan Controller

ESP32-S3 PID fan controller with ESPDash web dashboard and BLE Wi-Fi provisioning,
built for the Vishes seedling cabinet.

## Hardware

| Component      | Part                                   |
|----------------|----------------------------------------|
| MCU            | Seeed XIAO ESP32-S3                    |
| Fan controller | Adafruit EMC2101 (I2C 0x4C, PWM mode) |
| Temp probe     | DS18B20 one-wire sensor                |
| Fan type       | 4-wire PC fan (25 kHz PWM)             |

## Pin Assignments

{md_table(['Define', 'Value', 'Description'], [(n, v, c) for n, v, c in pins])}

## Timing Constants

{md_table(['Define', 'Value (ms)', 'Description'], [(n, v, c) for n, v, c in timing])}

## BLE Provisioning

| Setting      | Value                                     |
|--------------|-------------------------------------------|
| Service name | `{next((v for n,v,c in prov if 'NAME' in n), 'PROV_SeedlingFan')}` |
| PIN          | `{next((v for n,v,c in prov if 'POP' in n), '9116')}`              |
| App          | ESP BLE Provisioning by Espressif (iOS / Android) |

To provision or re-provision:

1. Wire D3 (GPIO 4) to GND and hold during reset.
2. Open the **ESP BLE Provisioning** app and scan for `{next((v for n,v,c in prov if 'NAME' in n), 'PROV_SeedlingFan')}`.
3. Enter PIN `{next((v for n,v,c in prov if 'POP' in n), '9116')}`, choose your network, and confirm.
4. Remove the jumper — the board reboots and connects automatically.

## Dashboard

Served at `http://<device-ip>/dash`.
Open `http://<device-ip>/` in Safari and use **Add to Home Screen** for a standalone iOS web clip.

| Widget           | Type    | Description                            |
|------------------|---------|----------------------------------------|
| Temperature      | Display | Live probe reading in °F               |
| Fan %            | Display | Current PID output (0–100%)            |
| RPM              | Display | Tachometer reading from EMC2101        |
| Probe Status     | Status  | Connected / Disconnected indicator     |
| Target Temp      | Slider  | Setpoint 60–90 °F (persisted to NVS)   |
| Kp / Ki / Kd     | Sliders | PID gains (persisted to NVS)           |
| Run Full On Error| Toggle  | Fan at 100% or 0% if probe is lost     |

## PID Defaults

| Parameter   | Default | Notes                                        |
|-------------|---------|----------------------------------------------|
| Target temp | 75 °F   | Persisted to NVS                             |
| Kp          | 2.0     | Proportional gain                            |
| Ki          | 0.1     | Integral gain                                |
| Kd          | 0.0     | Derivative gain                              |
| Direction   | REVERSE | Fan output increases when temp > setpoint    |
| Sample time | 2000 ms | Matches `CONTROL_INTERVAL_MS` in config.h    |

## Modules

{md_table(['Module', 'Description'], module_rows)}

## Getting Started

1. **Clone the repo**
   ```sh
   git clone https://github.com/your-username/vishes-fan-controller.git
   cd vishes-fan-controller
   ```

2. **Create your local config**
   ```sh
   cp src/config_local.h.example src/config_local.h
   ```
   Edit `src/config_local.h` and set your own `PROV_SERVICE_NAME` and `PROV_POP`.

3. **Open in VS Code** with the [PlatformIO IDE](https://platformio.org/platformio-ide) extension installed.

4. **Build and flash** using the tasks below.

---

## Build & Flash

Open this project in VS Code with the PlatformIO extension, then use **Terminal → Run Task**:

| Task                  | Action                              |
|-----------------------|-------------------------------------|
| PIO: Build            | Compile firmware                    |
| PIO: Upload           | Flash to connected board            |
| PIO: Monitor          | Open serial monitor at 115 200 baud |
| PIO: Upload + Monitor | Flash then open serial monitor      |

## Documentation

API docs are generated with [Doxygen](https://www.doxygen.nl/).
Run the **Docs: Generate + Open** VS Code task, or from a terminal:

```sh
python scripts/gen_readme.py   # regenerate this README
doxygen Doxyfile               # build HTML docs  (output: docs/html/index.html)
```

This README is consumed by Doxygen as the main page (`USE_MDFILE_AS_MAINPAGE = README.md`).
"""

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(readme)

print(f"README written -> {OUT}")
